window.AppTips = {
  items: [
    // --- ORIGINAL TIPS ---
    "TIP: THE BACKGROUND WEBGL MESH SYNCS TO THE LAST TWEAKED PHOTOSYNTH",
    "TIP: INCREASE 'P.ENV' TO CREATE PUNCHY KICKS AND DEEP 808 BASSES",
    "TIP: ROUTE AUDIO INTO A PHOTOSYNTH TO PROCESS IT THROUGH ITS FILTER & ADSR",
    "TIP: CLICK 'ASSIGN' ON AN LFO, THEN CLICK A KNOB TO MACRO AUTOMATE IT",
    "TIP: INCREASE 'FM AMT' TO MODULATE THE UNISON STACK WITH THE SUB OSCILLATOR",

    // --- ROUTING & UI WORKFLOW ---
    "TIP: DRAG AND DROP MODULES TO REORDER YOUR SIGNAL CHAIN INSTANTLY",
    "TIP: DOUBLE-CLICK ANY KNOB OR SLIDER TO RESET IT TO ITS DEFAULT VALUE",
    "TIP: USE THE UTILITY I/O MODULE TO GAIN STAGE BETWEEN HEAVY PROCESSING CHAINS",
    "TIP: HIDE THE VISUALIZER PANEL TO SAVE CPU CYCLES DURING HEAVY SESSIONS",
    "TIP: SAVE YOUR FAVORITE RACK COMBINATIONS AS PRESETS IN THE QUICK TWEAKS MENU",
    "TIP: RIGHT-CLICK A VIRTUAL CABLE TO INSTANTLY DISCONNECT A ROUTING PATH",
    "TIP: USE THE TAB KEY TO QUICKLY CYCLE THROUGH ACTIVE MODULE PANELS",
    "TIP: BYPASS MODULES BY CLICKING THEIR POWER ICON TO A/B TEST YOUR SOUND",
    "TIP: MULTIPLE SYNTHS CAN BE ROUTED TO A SINGLE REVERB BUS TO SAVE CPU",
    "TIP: WATCH THE MASTER OUT METER; RED MEANS YOUR AUDIO IS DIGITALLY CLIPPING",

    // --- MODULATION & SEQUENCING ---
    "TIP: ROUTE THE PROBABILITY SEQUENCER TO THE RHYTHM MODULE FOR EVOLVING DRUMS",
    "TIP: LFO RATES CAN BE SYNCED TO THE HOST TEMPO OR RUN IN FREE HERTZ MODE",
    "TIP: MAP AN LFO TO THE FILTER CUTOFF FOR CLASSIC DUBSTEP WOBBLE EFFECTS",
    "TIP: REDUCE SEQUENCER PROBABILITY TO ADD A HUMAN FEEL TO HI-HAT PATTERNS",
    "TIP: MODULATE THE REVERB DECAY TIME WITH AN LFO FOR BREATHING AMBIENT SPACES",
    "TIP: THE STEP SEQUENCER CAN DRIVE PITCH, VELOCITY, OR ANY ASSIGNED MACRO",
    "TIP: USE A SLOW, RANDOM LFO ON PANNING FOR A WIDER, MOVING STEREO IMAGE",
    "TIP: CHAIN TWO LFOS TOGETHER BY MAPPING ONE TO THE OTHER'S RATE",
    "TIP: AUTOMATE THE OTT THRESHOLD FOR RHYTHMIC PUMPING WITHOUT SIDECHAINING",
    "TIP: ADJUST THE LFO PHASE TO OFFSET MODULATION TIMING ACROSS MULTIPLE TARGETS",

    // --- SYNTHESIS & SOUND DESIGN ---
    "TIP: INCREASE UNISON VOICES AND DETUNE FOR MASSIVE, MODERN SUPER-SAWS",
    "TIP: SHORTEN THE AMP ENVELOPE RELEASE TIME FOR TIGHT, PLUCKY ARPEGGIOS",
    "TIP: ADD WHITE NOISE TO SYNTH LEADS TO HELP THEM CUT THROUGH A DENSE MIX",
    "TIP: GLIDE (PORTAMENTO) ONLY TRIGGERS WHEN PLAYING OVERLAPPING MIDI NOTES",
    "TIP: HARD SYNC THE OSCILLATORS AND MODULATE PITCH FOR METALLIC SCREAMS",
    "TIP: THE SUB OSCILLATOR BYPASSES THE UNISON STACK TO KEEP THE LOW END CLEAN",
    "TIP: USE THE WAVETABLE POSITION SLIDER TO FIND THE SWEET SPOT OF THE HARMONICS",
    "TIP: INCREASE FILTER DRIVE BEFORE COMPRESSION FOR WARMER, ANALOG-STYLE TONES",
    "TIP: A SLOW ATTACK ON A HIGH-PASS FILTER CREATES A SWEEPING, RISER EFFECT",
    "TIP: USE THE CHORD MEMORY FEATURE TO TRIGGER FULL HARMONIES WITH ONE FINGER",

    // --- EFFECTS & MIXING ---
    "TIP: USE THE OTT MODULE FOR AGGRESSIVE UPWARDS COMPRESSION ON WEAK SOUNDS",
    "TIP: TRIGGER THE SIDECHAIN MODULE WITH A KICK GHOST TRACK FOR CLASSIC EDM PUMPING",
    "TIP: CUT THE MUDDY LOW-MIDS (200-400HZ) WITH THE EQ TO CLEAR UP YOUR MIX",
    "TIP: USE THE AUTOFILTER MODULE'S ENVELOPE FOLLOWER FOR FUNKY AUTO-WAH EFFECTS",
    "TIP: HIGH-PASS ALL NON-BASS INSTRUMENTS AT 100HZ TO LEAVE ROOM FOR THE KICK",
    "TIP: WET REVERB SIGNALS PUSH SOUNDS INTO THE BACKGROUND OF THE SOUNDSTAGE",
    "TIP: APPLY GENTLE SATURATION BEFORE EQ TO HARMONICALLY ENRICH DULL SAMPLES",
    "TIP: USE THE PRO-REV MODULE'S FREEZE FUNCTION FOR INFINITE AMBIENT DRONES",
    "TIP: NARROW THE EQ Q-FACTOR FOR SURGICAL RINGING FREQUENCY REMOVAL",
    "TIP: WIDEN THE STEREO IMAGE OF HIGH FREQUENCIES, BUT KEEP SUB-BASS IN MONO",

    // --- SYSTEM & PERFORMANCE ---
    "TIP: EXPERIENCING AUDIO CRACKLE? INCREASE THE BUFFER SIZE IN QUALITY PROFILES",
    "TIP: THE WEB AUDIO API REQUIRES A CLICK ANYWHERE ON SCREEN BEFORE PRODUCING SOUND",
    "TIP: LOWER THE WEBGL FRAME RATE IN SETTINGS IF YOUR LAPTOP BATTERY DRAINS FAST",
    "TIP: USE THE MIDI LEARN FUNCTION TO MAP HARDWARE CONTROLLERS TO ON-SCREEN KNOBS",
    "TIP: EXPORT YOUR FINAL RACK CONFIGURATION AS A JSON FILE TO SHARE WITH OTHERS",
    "TIP: PRESS SPACEBAR TO QUICKLY PLAY AND PAUSE THE MASTER TRANSPORT",
    "TIP: THE PERFORMANCE MONITOR SHOWS REAL-TIME DSP LOAD; KEEP IT UNDER 80%",
    "TIP: PRO EDM TARGET: AIM FOR -7 TO -6 LUFS IN THE DROP FOR MAXIMUM LOUDNESS",
    "TIP: MAINTAIN A CREST FACTOR OF 8-10 DB TO KEEP YOUR DRUMS PUNCHY AND DYNAMIC",
    "TIP: EDM KICK TIP: FOCUS ATTACK AT 3-5 KHZ AND THE BODY AT 80-200 HZ",
    "TIP: ALWAYS HIGH-PASS THE MASTER BUSS AT 30 HZ TO REMOVE INAUDIBLE HEADROOM STEALERS",
    "TIP: PROS PUSH TRUE PEAK TO -0.3 DB FOR MORE IMPACT; -1.0 DB IS FOR STREAMING SAFETY",
    "TIP: USE SOFT CLIPPING BEFORE THE MASTER LIMITER TO INCREASE PERCEIVED LOUDNESS"
  ]
};